name: generate-json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN || github.token }}

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          HHW_LANG: ${{ secrets.HHW_LANG }}
        run: pnpm test

      - name: Upload
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shanghai
          bucket: monsterx
          assets: |
            abyss.beautify.json:/bot/abyss.beautify.json
            abyss.json:/bot/abyss.json

      - name: Commit
        uses: EndBug/add-and-commit@main
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: 更新深渊数据'
          add: |
            'abyss.beautify.json'
            'abyss.json'
